export const PROTOCOL_CONSTANTS = {
    // Limits
    MAX_HOST_CHILDREN: 5,
    MAX_NODE_CHILDREN: 3,
    MAX_ATTACH_ATTEMPTS: 10,
    MAX_REDIRECT_DEPTH: 5,

    // Timeouts & Intervals (ms)
    RAIN_INTERVAL: 1000,
    STALL_THRESHOLD: 3000,
    SUBTREE_REPORT_INTERVAL: 5000,
    HEALTH_CHECK_DEGRADED: 2000,
    HEALTH_CHECK_OFFLINE: 5000,

    // Caches
    DEDUP_CACHE_SIZE: 100,
    GAME_EVENT_CACHE_SIZE_HOST: 100,
    GAME_EVENT_CACHE_SIZE_NODE: 50,
    ACK_TRACKER_TIMEOUT: 10000,

    // Rate Limiter
    RATE_LIMIT_TOKENS: 5,
    RATE_LIMIT_WINDOW: 10000,
    RATE_LIMIT_BAN: 30000,
};
